### ISSUE TITLE
请问 Slider plugin 会出 react 的版本嘛，如何在 react 中使用....

### ISSUE THREAD

**Issue by ThomasChan** [antvis/g2-react#14]

**Comment by jaredleechn** [comment]
@simaQ

**Comment by kunsam** [comment]
同求，卡了下react 下G2.plugin是空的，所以也无法使用。

**Comment by simaQ** [comment]
已发， https://github.com/antvis/g2-plugin-slider，使用详见：https://github.com/antvis/g2-react/blob/master/examples/g2-plugin-slider.md

**Comment by jaredleechn** [comment]
online-demo: https://antvis.github.io/g2-react/examples/g2-plugin-slider.html
