### ISSUE TITLE
请问更新state后，为什么图表会使整个页面置顶?

### ISSUE THREAD

**Issue by kunsam** [antvis/g2-react#15]
只要带图表的组件状态更新，页面就🔝置顶了

**Comment by kunsam** [comment]
比如
 `export default class LineChart extends React.Component {
     ....
     render() {
       const TChart = createG2(chart => { ... });
       retrun <TChart {...props} />
     }
}`

只要LineChart组件中的state一更新页面就会自动置顶

**Comment by jaredleechn** [comment]
不在要 render 里面创建图表，这样你 props 更新都会重新创建

**Comment by jaredleechn** [comment]
在 constructor 里面创建 chart，render 方法通过 this 来渲染，可以参考例子 https://github.com/antvis/g2-react/blob/master/examples/higherWrapper.md

**Comment by FEliuyg** [comment]
我试了一下，效果也是一样的，state更新，图表还是显示不出来为空白。
因为我是切换不同状态，展示不同的数据，所有我在chart上加了个key，每种状态渲染对应不同的key，这样就好了@jaredleechn

**Comment by jaredleechn** [comment]
> 因为我是切换不同状态，展示不同的数据

dva 上的 store 发生变化，connect map 到你的 props 上，你只要

```
<this.Chart data={this.props.data} />
```

如果你想把数据保存在局部的 state，也是一样的道理，换数据是没问题的，g2-react 会判断引用地址发生变化就 changeData 的

**Comment by FEliuyg** [comment]
```
chart.source(data, {
  xDim: {
    type: 'cat',
    range: [0, 1]
  }
});
```
在react中， 怎么设置两边不留白。只看到有个这个设置，但是需要获取到data，不然不起作用。

**Comment by FEliuyg** [comment]
原来可以用
```
  chart.col(xDim, {
      type: 'cat',
      range: [0, 1]
  });
```

**Comment by guoqianli** [comment]
请问那个key加在那里的呢？在线等，急！！！@FEliuyg

**Comment by guoqianli** [comment]
结合dva，更新props时，数据更新，结果g2柱状图始终绘制不出来，找了好久，就在要放弃g2的时候，找到了解决办法，在componentWillReceiveProps的时候判断数据是否更新，如果更新则重新调用chart绘图，然后在shouldComponentUpdate的时候还是要再判断一下，数据没更新就return false，否则就算前一个状态没更新，但是一样的会走chart的changeData()，这个时候图表就渲染不出来了
