### ISSUE TITLE
柱状图source(data, colDefs)中的第二个参数colDefs要怎么传递进去呢?

### ISSUE THREAD

**Issue by laolu87** [antvis/g2-react#2]
试过了好像不行,源码好像也忽略了这个参数,请问如果需要我要怎么传递进去呢?

**Comment by dxq613** [comment]
也可以直接调用：

chart.col('dim',cfg);

**Comment by laolu87** [comment]
@dxq613 恩恩,谢谢了,按你说的这样设置,度量值是可以了,但是为什么我这样写:
```
  chart.col('sold', {alias: "销售量", min:0});
```
alias属性不起作用

**Comment by laolu87** [comment]
找到原因了,`chart.col`只要在构图之前调用就不会有问题了.
