### ISSUE TITLE
state更新但是图表不刷新的问题

### ISSUE THREAD

**Issue by suffrajet** [antvis/g2-react#30]
实际测试结果：这里的newData和oldData始终是相等的，导致不会刷新图表。
```
if (newData !== oldData) {
        this.chart.changeData(newData);
      }
```

**Comment by jaredleechn** [comment]
这是 react 的设计思想，如果你想告诉 react 数据发生了变更，一定是返回一个新的数组，而不是直接 push，所以这部分的判断是没有问题的


this.setState({ data: this.state.concat() })
