### ISSUE TITLE
"examples/g2-plugin-slider" can not work.  error: Plugin.Slider is not a constructor

### ISSUE THREAD

**Issue by Boboandhaifeng** [antvis/g2-react#33]
"examples/g2-plugin-slider" can not work.  error: Plugin.Slider is not a constructor

**Comment by jaredleechn** [comment]
@simaQ can you make a upgrade of dependencies like g2 and g2-plugin-slider?

**Comment by simaQ** [comment]
![image](https://cloud.githubusercontent.com/assets/6628666/25878620/b92aa644-355e-11e7-83fc-5ff7a9e1e6a2.png)

G2@2.3.x 版本做了升级，所以 g2-plugin-slider 版本需要升级至>=1.2.0 版本

https://github.com/antvis/g2-react/blob/master/package.json#L62

"g2-plugin-slider": "~1.2.0",

**Comment by Boboandhaifeng** [comment]
"g2": "2.2.7",
 "g2-plugin-slider": "^1.2.1",
 "g2-react": "^1.2.0",

这是目前的版本号  已经是新的了

**Comment by Boboandhaifeng** [comment]
我的 react 版本号 "react": "15.4.2",     而且用了 es6 语法， 所以创建组件的形式是下面这样， 会有影响吗？
class G2DemoPageS extends Component {
    constructor(props) {
        super(props);

        // 创建数据源
        var Frame = G2.Frame;
        var frame = new Frame(data);
        frame.addCol('trend', function(obj) {
            return (obj.start <= obj.end) ? 0 : 1;
        });
        console.log(frame);

        this.state = {
          data: frame,
          forceFit: true,
          width: 500,
          height: 250,
          plotCfg: {
            margin: [60, 120, 30],
            background: {
              fill: '#191821'
            }
          }
        }
    }
    render () {
        return (
            <div className='g2-demo clearfloat'>
                  <Chart
                                data={this.state.data}
                                width={this.state.width}
                                height={this.state.height}
                                plotCfg={this.state.plotCfg}
                                forceFit={this.state.forceFit} />

                    <div id="slider"></div>
            </div>
        );
    }
}

**Comment by jaredleechn** [comment]
看一下实际安装的版本是否满足需求？

rm -rf node_modules && npm i

cat node_modules/g2-plugin-slider/package.json
