### ISSUE TITLE
坐标轴精度问题

### ISSUE THREAD

**Issue by htlhenry** [antvis/g2-react#52]
问题：
![image](https://user-images.githubusercontent.com/13076222/29158562-11a45014-7dde-11e7-9958-70b1cec730d7.png)
问题描述:
我的数据详见下面项目样例，具体问题就是：我的数据都是1.xx的2位浮点数，但是显示的Y轴是0000000001-0000000000x这样的整数，不知为何，令人费解。
项目样例：
```
https://github.com/htlhenry/G2-issue
```

**Comment by simaQ** [comment]
这个问题已经修复了，G2@2.3.10
