### ISSUE TITLE
不会再dva里面用g2，有教程或者文档不

### ISSUE THREAD

**Issue by junmaqiang** [antvis/g2-react#8]
好困哪呀，看到在react下用，没看到在dva部署的项目中用g2 希望有知道的伙伴提供下参考

**Comment by junmaqiang** [comment]
`
/*
  数据列表
*/

import React from 'react';
import createG2 from 'g2-react';
import { Stat } from 'g2';


const Pie = createG2(chart => {
  chart.coord('theta');
  chart.intervalStack().position(Stat.summary.proportion()).color('cut');
  chart.render();
});


const List = () => {

  // 渲染页面
  return (
    <div>
        <Pie
            data={data}
            width={this.state.width}
            height={this.state.height}
            plotCfg={this.state.plotCfg}
            ref="c1"
        />
    </div>
  );
};

export default List;
`

**Comment by wenshiqi0** [comment]
你这个周末可能跑啊 用了一个stateless的组件，但是内部渲染却又用state来传递数据，这不是G2和dva的问题，而是你dva用的有问题。

**Comment by jaredleechn** [comment]
把 chart 的创建放在 Component 内部，数据获取通过 props

```jsx
class Component extends React.Component {
  constructor(...argus) {
    super(...argus);
    this.Chart = createG2(chart => {});
  }
  render() {
    return (<this.Chart data={this.props.data} />);
  }
}
