### ISSUE TITLE
chart.source第二个参数怎么传过去

### ISSUE THREAD

**Issue by xiehurricane** [antvis/g2-react#9]
现象：
参照https://antvis.github.io/g2-react/examples/line.html 示例写一个折线图。
示例有一段：

chart.source(frame, {
    date: {
      type: 'time',
      mask: 'yyyy.mm',
      tickCount: 12
    },
    value: {
      alias: 'Temperature, ºF'
    }
  });

问题：
不知道怎么在react里实现。

**Comment by jaredleechn** [comment]
目前可以在 createG2 里面手动处理

```
createG2(chart => {
  chart.source(data, defs);
})
```

See more #10

**Comment by FEliuyg** [comment]
@jaredleechn 
```
createG2(chart => {
  chart.source(data, defs);
})
```
这种处理，在react会报data is undefined, 怎么处理第二个参数

**Comment by jaredleechn** [comment]
@simaQ 评估下，如果把 defs 作为可变的 props 在 g2 层会不会有什么问题？
